### ISSUE TITLE
OpenChat - Images are not posted if no text is submitted

### ISSUE THREAD

**Issue by lkellar** [puffyboa/puffyboa.xyz#1]
I'm not sure if this is intentional or not, but when an image is uploaded and submitted without text, nothing happens. The image is not visible and there is no error message

If you would like all images to be accompanied by text, I would at least recommend an error of some sort.

**Comment by jpsank** [comment]
[Fixed it](https://github.com/puffyboa/puffyboa.xyz/commit/ddd7fd8bc8ba751415882ea013cad86662810e0c)
